name: 'Upload'
description: 'Upload package to server'
inputs:
  url: 
    description: 'Upload URL'
    required: true
  pass:
    description: 'Upload password'
    required: true
  pkg-name:
    description: 'Name of the file to upload'
    required: true

runs:
  using: "composite"
  steps: 
    - run: curl -v -F "appFile=@${{ inputs.pkg-name }}" --form-string "pass=${{ inputs.pass }}" ${{ inputs.url }}
      shell: bash
